export const GESTIONS_ALMERA = [
  'Seguridad del Paciente',
  'Documentos',
  'Riesgos',
  'Planes de Mejora',
  'Mecanismos de Integración',
  'Indicadores de Gestión y Normativos',
  'BSC',
  'PQRSF',
  'Encuestas',
  'Evaluaciones',
]

export const PROCESOS_MAP = [
  'Gestión del Direccionamiento Estratégico',
  'Gestión de Calidad y Mejoramiento Institucional',
  'Gestión de Acceso',
  'Atención en Urgencias',
  'Atención Ambulatoria',
  'Apoyo Hospitalario',
  'Apoyo Diagnóstico',
  'Apoyo Terapéutico',
  'Atención Humanizada',
  'Prestación de Servicios de Investigación',
  'Gestión Financiera',
  'Gestión de la Tecnología',
  'Gerencia de Servicios',
  'Gestión del Ambiente Físico',
  'Gerencia de las Comunicaciones',
  'Gestión del Talento Humano',
  'Gestión de Acuerdos y Alianzas',
  'Evaluación, Monitoreo y Análisis',
  'Gestión de Enfoque y Gestión del Riesgo',
]
