import { useEffect,useMemo,useState } from 'react'
import { AlertTriangle,Plus,RefreshCw,X } from 'lucide-react'
import { Badge,Button,Card,Field,PageHeader,SearchBox,StatCard,StatusBadge } from '@/shared/ui'
import { almeraService } from '../services/almeraService'
import type { AlmeraCatalogs,Assistance,AssistanceMetrics } from '../types'

const empty={subject:'',processId:'',almeraModuleId:'',requesterName:'',requesterPosition:'',requesterContact:'',requestChannel:'CORREO',description:'',priority:'MEDIA',commitmentAt:'',responsibleMembershipId:'',observations:''}
export default function AlmeraPage(){
 const [rows,setRows]=useState<Assistance[]>([]),[catalogs,setCatalogs]=useState<AlmeraCatalogs>({processes:[],modules:[],responsibles:[]}),[metrics,setMetrics]=useState<AssistanceMetrics>({total:0,open:0,completed:0,overdue:0,compliance:'0'}),[query,setQuery]=useState(''),[form,setForm]=useState(empty),[show,setShow]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const load=async()=>{try{setError('');const [a,c,m]=await Promise.all([almeraService.assistances(),almeraService.catalogs(),almeraService.metrics()]);setRows(a);setCatalogs(c);setMetrics(m)}catch(e){setError(e instanceof Error?e.message:'Error inesperado')}}
 useEffect(()=>{void load()},[])
 const filtered=useMemo(()=>rows.filter(x=>`${x.code} ${x.subject} ${x.process_name} ${x.module_name} ${x.requester_name}`.toLowerCase().includes(query.toLowerCase())),[rows,query])
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await almeraService.createAssistance({...form,commitmentAt:form.commitmentAt||null,responsibleMembershipId:form.responsibleMembershipId||null});setForm(empty);setShow(false);await load()}catch(e){setError(e instanceof Error?e.message:'No se pudo registrar')}finally{setBusy(false)}}
 return <div className="module-workspace mx-auto max-w-7xl space-y-6">
  <PageHeader eyebrow="Módulo central" title="Gestión ALMERA" description="Seguimiento real y trazable de asistencias técnicas institucionales." actions={<><Button onClick={()=>setShow(true)}><Plus size={16}/>Nueva asistencia</Button><Button variant="secondary" onClick={()=>void load()}><RefreshCw size={16}/>Actualizar</Button></>}/>
  {error&&<div className="rounded-xl border border-red-400/30 bg-red-400/10 p-3 text-sm text-red-200">{error}</div>}
  <section className="metric-strip"><StatCard label="Total" value={metrics.total} detail="Asistencias registradas" tone="info"/><StatCard label="Abiertas" value={metrics.open} detail="Requieren seguimiento" tone="warning"/><StatCard label="Completadas" value={metrics.completed} detail="Cerradas con trazabilidad" tone="success"/><StatCard label="Vencidas" value={metrics.overdue} detail={`${metrics.compliance}% de cumplimiento`} tone="danger"/></section>
  <Card className="p-4"><SearchBox value={query} onChange={setQuery} placeholder="Buscar por código, asunto, proceso, módulo o solicitante"/></Card>
  <Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-white/10 p-5"><div><p className="eyebrow">Bandeja operativa</p><h2 className="mt-1 text-xl font-black">Asistencias técnicas</h2></div><Badge tone="info">{filtered.length} registros</Badge></div><div className="overflow-x-auto"><table className="data-table min-w-[1100px]"><thead><tr><th>Código / asunto</th><th>Proceso / módulo</th><th>Solicitante</th><th>Prioridad</th><th>Compromiso</th><th>Responsable</th><th>Estado</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><strong>{x.code}</strong><span className="mt-1 block text-sm text-slate-400">{x.subject}</span></td><td><strong>{x.process_name}</strong><span className="mt-1 block text-sm text-slate-400">{x.module_name}</span></td><td>{x.requester_name}</td><td><Badge tone={x.priority==='CRITICA'?'danger':x.priority==='ALTA'?'warning':'info'}>{x.priority}</Badge></td><td>{x.commitment_at?new Date(x.commitment_at).toLocaleString('es-CO'):'Sin fecha'}{x.overdue&&<span className="mt-1 flex items-center gap-1 text-xs text-red-300"><AlertTriangle size={12}/>Vencida</span>}</td><td>{x.responsible_name||'Sin asignar'}</td><td><StatusBadge status={x.status.replaceAll('_',' ')}/></td></tr>)}{!filtered.length&&<tr><td colSpan={7} className="py-12 text-center text-slate-400">No hay asistencias registradas con estos filtros.</td></tr>}</tbody></table></div></Card>
  {show&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/80 p-4"><Card className="max-h-[92vh] w-full max-w-3xl overflow-y-auto p-6"><div className="flex justify-between"><div><p className="eyebrow">Registro</p><h2 className="text-2xl font-black">Nueva asistencia técnica</h2></div><button onClick={()=>setShow(false)}><X/></button></div><form className="mt-6 grid gap-4 md:grid-cols-2" onSubmit={submit}><Field label="Asunto"><input required value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/></Field><Field label="Solicitante"><input required value={form.requesterName} onChange={e=>setForm({...form,requesterName:e.target.value})}/></Field><Field label="Proceso"><select required value={form.processId} onChange={e=>setForm({...form,processId:e.target.value})}><option value="">Seleccionar</option>{catalogs.processes.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Módulo ALMERA"><select required value={form.almeraModuleId} onChange={e=>setForm({...form,almeraModuleId:e.target.value})}><option value="">Seleccionar</option>{catalogs.modules.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Prioridad"><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{['BAJA','MEDIA','ALTA','CRITICA'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Fecha de compromiso"><input type="datetime-local" value={form.commitmentAt} onChange={e=>setForm({...form,commitmentAt:e.target.value})}/></Field><Field label="Responsable"><select value={form.responsibleMembershipId} onChange={e=>setForm({...form,responsibleMembershipId:e.target.value})}><option value="">Sin asignar</option>{catalogs.responsibles.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></Field><Field label="Contacto"><input value={form.requesterContact} onChange={e=>setForm({...form,requesterContact:e.target.value})}/></Field><div className="md:col-span-2"><Field label="Descripción de la solicitud"><textarea required rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field></div><div className="md:col-span-2 flex justify-end gap-3"><Button type="button" variant="secondary" onClick={()=>setShow(false)}>Cancelar</Button><Button type="submit" disabled={busy}>{busy?'Guardando...':'Registrar asistencia'}</Button></div></form></Card></div>}
 </div>
}
